import { Volume } from '../../interfaces';

export const volumeData: Volume[] = [
  {
    id: 1,
    name: 'Revista Científica',
    tomo: 'Vol. 1',
    editorial: 'Editorial XYZ',
    publicationDate: 'Nov 21',
    description: 'Un volumen interesante sobre ciencia',
    authors: ['Autor A', 'Autor B'],
    genre: 'Científico',
    isbn: '978-1234567890',
    contentLink: 'http://revista.repositoriounipol.com/volumes',
    img: '/images/wan1.png',
  },
  {
    id: 2,
    name: 'Libro de Historia',
    tomo: 'Vol. 2',
    editorial: 'Editorial ABC',
    publicationDate: 'Oct 18',
    description: 'Explorando eventos históricos importantes',
    authors: ['Historiador X'],
    genre: 'Histórico',
    isbn: '978-0987654321',
    contentLink: 'https://ejemplo.com/libro-historia-1',
    img: '/images/wan2.webp',
  },
  {
    id: 3,
    name: 'Antología de Poesía',
    tomo: 'Vol. 3',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Ene 25',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-3',
    img: '/images/wan3.jpeg',
  },
  {
    id: 4,
    name: 'Libro de Seguridad Social',
    tomo: 'Vol. 4',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Nov 15',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-4',
    img: '/images/wan4.png',
  },
  {
    id: 5,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 5',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-5',
    img: '/images/wan5.jpeg',
  },

  {
    id: 6,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 6',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-6',
    img: '/images/wan6.png',
  },

  {
    id: 7,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 7',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-7',
    img: '/images/wan7.png',
  },

  {
    id: 8,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 8',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-8',
    img: '/images/wan8.png',
  },

  {
    id: 9,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 9',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-9',
    img: '/images/wan9.png',
  },

  {
    id: 10,
    name: 'Revista de Espionaje',
    tomo: 'Vol. 10',
    editorial: 'Editorial Poesía Express',
    publicationDate: 'Dic 20',
    description: 'Una colección de poemas inspiradores',
    authors: ['Poeta Y', 'Poeta Z'],
    genre: 'Poesía',
    isbn: '978-9876543210',
    contentLink: 'https://ejemplo.com/antologia-poesia-vol-10',
    img: '/images/wan10.png',
  },
];
