import { Year } from '../../interfaces';
import { volumeData } from './volumeData';

export const yearData: Year[] = [
  {
    id: 1,
    name: '2023',
    description: 'Dos mil veintitrés',
    volumes: [
      volumeData[0],
      volumeData[1],
      volumeData[2],
      volumeData[3],
      volumeData[4],
      volumeData[5],
      volumeData[6],
      volumeData[7],
      volumeData[8],
      volumeData[9],
    ],
  },
  {
    id: 2,
    name: '2024',
    description: 'Dos mil veinticuatro',
    volumes: [volumeData[0], volumeData[1], volumeData[2]],
  },
  {
    id: 3,
    name: '2025',
    description: 'Dos mil veinticinco',
    volumes: [volumeData[2]],
  },
  { id: 4, name: '2026', description: 'Dos mil veintiséis', volumes: [] },
  { id: 5, name: '2027', description: 'Dos mil veintisiete', volumes: [] },
  { id: 6, name: '2028', description: 'Dos mil veintiocho', volumes: [] },
  { id: 7, name: '2029', description: 'Dos mil veintinueve', volumes: [] },
  { id: 8, name: '2030', description: 'Dos mil treinta', volumes: [] },
  { id: 9, name: '2031', description: 'Dos mil treintiun', volumes: [] },
  { id: 10, name: '2032', description: 'Dos mil treintidos', volumes: [] },
  { id: 11, name: '2033', description: 'Dos mil treintitres', volumes: [] },
  { id: 12, name: '2034', description: 'Dos mil treinticuatro', volumes: [] },
  { id: 13, name: '2035', description: 'Dos mil treinticinco', volumes: [] },
  { id: 14, name: '2036', description: 'Dos mil treintiséis', volumes: [] },
  { id: 15, name: '2037', description: 'Dos mil treintisiete', volumes: [] },
  { id: 16, name: '2038', description: 'Dos mil treintiocho', volumes: [] },
  { id: 17, name: '2039', description: 'Dos mil treintinueve', volumes: [] },
  { id: 18, name: '2040', description: 'Dos mil cuarenta', volumes: [] },
  { id: 19, name: '2041', description: 'Dos mil cuarentiun', volumes: [] },
  { id: 20, name: '2042', description: 'Dos mil cuarentidos', volumes: [] },
  // { id: 21, name: '2043', description: 'Dos mil cuarentitres', volumes: [] },
  // { id: 22, name: '2044', description: 'Dos mil cuarenticuatro', volumes: [] },
  // { id: 23, name: '2045', description: 'Dos mil cuarenticinco' },
  // { id: 24, name: '2046', description: 'Dos mil cuarentiséis' },
  // { id: 25, name: '2047', description: 'Dos mil cuarentisiete' },
  // { id: 26, name: '2048', description: 'Dos mil cuarentiocho' },
  // { id: 27, name: '2049', description: 'Dos mil cuarentinueve' },
  // { id: 28, name: '2050', description: 'Dos mil cincuenta' },
  // { id: 29, name: '2051', description: 'Dos mil cincuntiun' },
];
