version: '3.8'

services:
  db:
    image: mongo:3.6
    container_name: db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/data/db

volumes:
  db_data: