import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Montserrat, Roboto, Lato, Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Container from '@/components/Container';

const montserrat = Montserrat({ subsets: ['latin'] });
const roboto = Roboto({ weight: '400', subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'], display: 'swap' });
const lato = Lato({ weight: '100', subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <meta
        name='format-detection'
        content='telephone=no, date=no, email=no, address=no'
      />
      <body>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>{' '}
    </html>
  );
}
