import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Roboto, Lato, Inter} from 'next/font/google';
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import SessionAuthProvider from './session/SessionAuthProvider'
import { SessionProvider } from 'next-auth/react'

const montserrat = Montserrat({ subsets: ['latin'] })
const roboto = Roboto ({ weight: '400',subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'], display: 'swap'});
const lato = Lato({ weight: '100', subsets: ['latin'], display: 'swap'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header/>
          {children}
        <Footer/>
      </body>
      </html>
  )
}